# Generated by Django 5.0.3 on 2024-03-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('EmailID', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('PhoneNo', models.BigIntegerField()),
            ],
        ),
    ]
