# Generated by Django 5.0.3 on 2024-03-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(upload_to='static/assets/images/camps/')),
                ('Place', models.CharField(max_length=30)),
                ('Avalilability', models.CharField(max_length=30)),
            ],
        ),
    ]
